### PR TITLE
Feature/samething

### PR DESCRIPTION
**Pull request by aolieman**
I'd like some feedback on the `SameThingConverter` that I implemented in response to the discussion in #1 . This is a complete and working implementation, but I did come across some things that I could improve on the microservice side. I would suggest holding off on a merge for a couple of days to give me a chance to work on those (efficiency) improvements.

I have not yet done the following, and would like some input:
- [ ] update the CLI to work with the new converter
- [x] make the STS url/endpoint configurable
- [ ] update documentation

### CODE REVIEW

**Review by wetneb — APPROVED** [review]
Looks great to me, thanks a lot!

**Comment by wetneb** [comment]
About the CLI, I am not sure how to proceed. The `--mode` parameter is currently used to select a converter, and implicitly a conversion method at the same time (the one implemented by the converter). As a user I would find it nicer if I could select independently the source and target namespace, and the conversion method (SameThing, SPARQL, local index…). That probably requires changing the way `URIConverter` instances are registered.

**Comment by aolieman** [comment]
I ran out of the time I had available to work on this for the time being. Made all the changes I wanted, but didn't get as far as making a `URIConverter` registry. Usually I would solve this with a metaclass, but for `nifconverter` , it could be as simple as `CONVERTERS = {cls.__name__: cls for cls in URIConverter.__subclasses__()}`.

The simplest solution I could imagine working for the CLI now, with only two converter classes being implemented, is to replace `--mode` with `--source` and `--target`. Since `SameThingConverter` only takes a target parameter, it could be the default when only `--target` is provided by the user. If `--source` is also specified, the class selection could follow the same logic as is currently done with the mode parameter.

You should be able to push to my feature branch, so feel free to choose and implement the solution you prefer.

**Comment by wetneb** [comment]
Thanks very much @aolieman for this, I will add the CLI support.

**Comment by aolieman** [comment]
This is wonderful, thank you!

**Pull request merged**
